# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for zest
	pod 'GooglePlaces'
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'

  target 'zestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'zestUITests' do
    # Pods for testing
  end

end
